title: Tiny_ESC
lang: zh-CN
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

defaults:
  - scope:
      path: ""
    values:
      layout: default

nav:
  - title: 简介
    url: /
    aliases:
      - /docs/intro.html
  - title: 快速开始
    url: /docs/quick-start.html
  - title: 原理图
    url: /docs/schematic.html
  - title: 编译和烧录
    url: /docs/build-flash.html
  - title: 性能调优
    url: /docs/performance-tuning.html
  - title: 电机控制
    url: /docs/motor-control.html
