title: Tiny_ESC
lang: zh-CN
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

defaults:
  - scope:
      path: ""
    values:
      layout: default

nav:
  - title: 简介
    url: /
    aliases:
      - /docs/intro.html
  - title: 电机控制
    url: /docs/motor-control.html
